id: P009075
initial_creation_type: ocr
source_metadata:
  id: bdr:W28800
  title: གུ་རུའི་མཛད་རྣམ་མ་འོངས་བསྟན་སོགས་ཀྱི་དཀར་ཆག་གསལ་བའི་མེ་ལོང
  author: ''
  volumes:
    d6f9ea6bec444cd99b744aaaa9f94de2:
      image_group_id: I4642
      title: ''
      volume_number: 1
      total_pages: 22
      base_file: v001.txt
