id: IC4330008
legacy_id: P009075
ocr_import_info:
  bdrc_scan_id: W28800
  source: bdrc
  ocr_info:
    timestamp: '2020-03-21T14:01:27'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T08:42:09.299760+00:00'
last_modified: 2022-09-02 16:42:22.740168
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W28800
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW28800
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གུ་རུའི་མཛད་རྣམ་མ་འོངས་བསྟན་སོགས་ཀྱི་དཀར་ཆག་གསལ་བའི་མེ་ལོང་།
statistics:
  ocr_word_mean_confidence_index: 0.8220446571723047
  ocr_word_median_confidence_index: 0.9100000262260437
quality: null
bases:
  I4642:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4642
      total_pages: 22
      volume_number: 1
      volume_pages_bdrc_intro: 0
    order: 1
    base_file: I4642.txt
    statistics:
      ocr_word_median_confidence_index: 0.9100000262260437
      ocr_word_mean_confidence_index: 0.8220446571723047
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
